# Generated by Django 5.1.2 on 2024-11-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attention', '0006_certificado'),
        ('core', '0010_delete_audituser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('S', 'Solicitado'), ('R', 'Realizado')], max_length=20, verbose_name='Tipo de Examen')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
        ),
        migrations.RemoveField(
            model_name='costosatencion',
            name='atencion',
        ),
        migrations.AddField(
            model_name='atencion',
            name='valor_consulta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor de Consulta'),
        ),
        migrations.AlterField(
            model_name='detalleatencion',
            name='atencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_recetados', to='attention.atencion', verbose_name='Cabecera de Atención'),
        ),
        migrations.AlterField(
            model_name='detalleatencion',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='core.medicamento', verbose_name='Medicamento'),
        ),
        migrations.CreateModel(
            name='DetalleExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField()),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes_realizados', to='attention.atencion')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='realizados', to='attention.examen')),
            ],
            options={
                'verbose_name': 'Detalle de Examen',
                'verbose_name_plural': 'Detalles de Examen',
                'ordering': ['atencion'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('PAYPAL', 'PayPal')], max_length=20, null=True, verbose_name='Método de Pago')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pago')),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='attention.atencion')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta'), ('MEDICAMENTO', 'Medicamento'), ('EXAMEN', 'Examen'), ('SERVICIO', 'Servicio Adicional')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='attention.factura')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_prestados', to='attention.atencion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestaciones', to='attention.serviciosadicionales')),
            ],
        ),
        migrations.DeleteModel(
            name='CostoAtencionDetalle',
        ),
        migrations.DeleteModel(
            name='CostosAtencion',
        ),
    ]
